
const app=document.getElementById("app");
const CFG=window.WITH_WELFARE_CONFIG||{};
const SUPABASE_URL=String(CFG.SUPABASE_URL||"").trim().replace(/\/rest\/v1\/?$/,"").replace(/\/+$/,"");
const SUPABASE_KEY=String(CFG.SUPABASE_ANON_KEY||"").trim();
const supabaseClient=(SUPABASE_URL&&SUPABASE_KEY&&window.supabase)?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
let cloudReady=false, cloudHydrating=false, saveTimer=null, cloudStatus="로컬 모드";
let session=JSON.parse(localStorage.getItem("wm_session_v17")||"null");
let page="home", loginTab="user", adminTab="dashboard", previewCondolenceId=null, calMonth=new Date();

const initialState=()=>({
  settings:{logo:"",homeBadge:"Company Welfare Platform",homeTitle:"(주)위드메디컬 복지몰",homeDescription:"임직원을 위한 숙소예약, 경조사, 행사, 할인, 휴가지원사업 신청 시스템입니다.",annualNightLimit:10,nightlyPrice:270000,bank:"국민은행 123456-01-789012 (주)위드메디컬"},
  admins:[{id:"admin1",name:"김경진",loginId:"with1905",password:"withm*1905",role:"admin",dept:"관리자"}],
  users:[],
  menu:{stay:{name:"숙소예약",enabled:true},family:{name:"경조사",enabled:true},event:{name:"행사",enabled:true},discount:{name:"할인",enabled:true},vacation:{name:"휴가지원사업",enabled:true},notice:{name:"공지",enabled:true}},
  rooms:[
    {id:"stella",name:"스텔라동",basePeople:5,maxPeople:8,address:"제주특별자치도 서귀포시 안덕면 사계북로41번길 27-45, 사계펜션",photos:[],manual:""},
    {id:"solar",name:"솔라동",basePeople:5,maxPeople:8,address:"제주특별자치도 서귀포시 안덕면 사계북로41번길 27-45, 사계펜션",photos:[],manual:""}
  ],
  policies:[{id:"self",name:"본인 사용",discountRate:100,paymentRequired:false},{id:"family",name:"직계가족",discountRate:100,paymentRequired:false},{id:"friend",name:"지인",discountRate:50,paymentRequired:true}],
  reservations:[],
  condolenceTypes:[{id:"ct1",name:"결혼",desc:"결혼 축하 지원",amount:300000},{id:"ct2",name:"출산",desc:"출산 축하 지원",amount:300000},{id:"ct3",name:"장례",desc:"장례 조의 지원",amount:500000},{id:"ct4",name:"생일",desc:"생일 복지",amount:100000},{id:"ct5",name:"기타",desc:"기타 경조사",amount:100000}],
  condolences:[],
  events:[{id:"ev1",title:"사내 행사",date:"",limit:0,memo:"",open:true}],
  eventApplications:[],
  discounts:[{id:"movie",category:"문화",title:"영화무료상영권",rate:"무료",method:"선착순 5명 신청 접수 후 관리자 확인",link:"",applyEnabled:true,limitCount:5}],
  discountApplications:[],
  vacationSupport:[],
  notices:[],
  auditLogs:[]
});
let state=JSON.parse(localStorage.getItem("wm_state_v17")||"null")||initialState();

function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function toast(msg){const t=document.createElement("div");t.className="toast";t.innerText=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
function save(){localStorage.setItem("wm_state_v17",JSON.stringify(state));scheduleCloudSave()}
function scheduleCloudSave(){if(!supabaseClient||!cloudReady||cloudHydrating)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveCloudState,500)}
async function saveCloudState(){try{const {error}=await supabaseClient.from("app_state").upsert({id:"main",data:state,updated_at:new Date().toISOString()});if(error)throw error;cloudStatus="Supabase 저장 완료"}catch(e){console.error(e);cloudStatus="Supabase 저장 실패"}}
async function initCloud(){if(!supabaseClient){cloudStatus="Supabase 미연결";render();return}try{const {data,error}=await supabaseClient.from("app_state").select("data").eq("id","main").maybeSingle();if(error)throw error;if(data&&data.data&&Object.keys(data.data).length){cloudHydrating=true;state=mergeState(initialState(),data.data);normalize();localStorage.setItem("wm_state_v17",JSON.stringify(state));cloudHydrating=false;cloudReady=true;cloudStatus="Supabase 연결 완료"}else{normalize();cloudReady=true;await saveCloudState()}render()}catch(e){console.error(e);cloudStatus="Supabase 연결 실패";render()}}
function mergeState(base, incoming){return {...base,...incoming,settings:{...base.settings,...(incoming.settings||{})},menu:{...base.menu,...(incoming.menu||{})}}}
function normalize(){state.rooms=(state.rooms||[]).map(r=>({...r,name:r.name==="솔레동"?"솔라동":r.name,manual:r.manual||"",photos:r.photos||[]}));state.rooms=state.rooms.filter((r,i,a)=>["스텔라동","솔라동"].includes(r.name)&&a.findIndex(x=>x.name===r.name)===i);["스텔라동","솔라동"].forEach((n,i)=>{if(!state.rooms.find(r=>r.name===n))state.rooms.push({id:i?"solar":"stella",name:n,basePeople:5,maxPeople:8,address:"제주 사계펜션",photos:[],manual:""})});state.vacationSupport=state.vacationSupport||[];state.eventApplications=state.eventApplications||[];state.discountApplications=state.discountApplications||[];state.auditLogs=state.auditLogs||[]}
function money(n){return Number(n||0).toLocaleString()+"원"}
function onlyDigits(v){return String(v||"").replace(/\D/g,"")}
function user(){if(!session)return null;return session.role==="admin"?state.admins.find(a=>a.id===session.id):state.users.find(u=>u.id===session.id)}
function pageLabel(k){return (state.menu[k]||{}).name||k}
function enabled(k){return k==="home"||k==="admin"||k==="mypage"||(state.menu[k]&&state.menu[k].enabled)}
function setPage(p){if(!enabled(p))return toast("비활성 메뉴입니다.");page=p;render();scrollTo(0,0)}
function logout(){session=null;localStorage.removeItem("wm_session_v17");render()}
function audit(action,detail){state.auditLogs.unshift({id:uid(),actor:user()?.name||"시스템",action,detail,createdAt:new Date().toLocaleString()});state.auditLogs=state.auditLogs.slice(0,300)}

function loginView(){app.innerHTML=`<div class="loginbox panel"><div class="brand"><div class="logo">${state.settings.logo?`<img src="${state.settings.logo}">`:"W"}</div><div><b>WITH Welfare Mall</b><small>(주)위드메디컬 복지몰</small></div></div><h1>복지몰 로그인</h1><div class="tabs">${["user","signup","reset","admin"].map((t,i)=>`<button class="${loginTab===t?'active':''}" onclick="loginTab='${t}';render()">${["직원 로그인","회원가입","비밀번호 초기화","관리자"][i]}</button>`).join("")}</div>${loginTab==="user"?`<form class="form" onsubmit="loginUser(event)"><label class="wide">이름<input name="name" required></label><label class="wide">휴대폰 번호<input name="phone" placeholder="01012345678" required></label><label class="wide">비밀번호<input type="password" name="password" required></label><button class="wide">직원 로그인</button></form>`:""}${loginTab==="signup"?`<form class="form" onsubmit="signup(event)"><label>이름<input name="name" required></label><label>사원번호 선택<input name="empNo"></label><label>생년월일<input type="date" name="birth" required></label><label>휴대폰 번호<input name="phone" placeholder="01012345678" required></label><label>부서<input name="dept"></label><label>비밀번호<input type="password" name="password" required></label><label class="wide">비밀번호 확인<input type="password" name="password2" required></label><button class="wide">회원가입 신청</button></form>`:""}${loginTab==="reset"?`<form class="form" onsubmit="toast('관리자에게 비밀번호 초기화를 요청해 주세요.');event.preventDefault()"><label class="wide">이름<input required></label><label class="wide">휴대폰 번호<input required></label><button class="wide">초기화 요청</button></form>`:""}${loginTab==="admin"?`<form class="form" onsubmit="loginAdmin(event)"><label class="wide">관리자 ID<input name="loginId" value="with1905" required></label><label class="wide">비밀번호<input type="password" name="password" required></label><button class="wide">관리자 로그인</button></form>`:""}</div>`}
function loginUser(e){e.preventDefault();const f=new FormData(e.target);const u=state.users.find(x=>x.name===f.get("name")&&onlyDigits(x.phone)===onlyDigits(f.get("phone"))&&x.password===f.get("password"));if(!u)return toast("로그인 정보가 일치하지 않습니다.");if(u.status!=="승인")return toast("관리자 승인 후 로그인 가능합니다.");session={role:"user",id:u.id};localStorage.setItem("wm_session_v17",JSON.stringify(session));render()}
function loginAdmin(e){e.preventDefault();const f=new FormData(e.target);const a=state.admins.find(x=>x.loginId===f.get("loginId")&&x.password===f.get("password"));if(!a)return toast("관리자 정보가 일치하지 않습니다.");session={role:"admin",id:a.id};localStorage.setItem("wm_session_v17",JSON.stringify(session));render()}
function signup(e){e.preventDefault();const f=new FormData(e.target);if(f.get("password")!==f.get("password2"))return toast("비밀번호가 일치하지 않습니다.");const phone=onlyDigits(f.get("phone"));if(state.users.some(u=>onlyDigits(u.phone)===phone))return toast("이미 가입된 휴대폰 번호입니다.");state.users.push({id:uid(),name:f.get("name"),empNo:f.get("empNo"),birth:f.get("birth"),phone,dept:f.get("dept"),password:f.get("password"),status:"대기",createdAt:new Date().toLocaleString()});save();toast("회원가입 신청 완료");loginTab="user";render()}

function layout(content){const u=user();const nav=[["home","홈"],["stay",pageLabel("stay")],["family",pageLabel("family")],["event",pageLabel("event")],["discount",pageLabel("discount")],["vacation",pageLabel("vacation")],["notice",pageLabel("notice")]];return `<div class="top"><div class="topin"><div class="brand"><div class="logo">${state.settings.logo?`<img src="${state.settings.logo}">`:"W"}</div><div><b>WITH Welfare Mall</b><small>${u?.name||""} · ${session.role==="admin"?"관리자":"직원"}</small></div></div><div class="nav">${nav.filter(n=>enabled(n[0])).map(n=>`<button class="${page===n[0]?'active':''}" onclick="setPage('${n[0]}')">${n[1]}</button>`).join("")}${session.role==="admin"?`<button class="${page==='admin'?'active':''}" onclick="setPage('admin')">관리자</button>`:`<button class="${page==='mypage'?'active':''}" onclick="setPage('mypage')">내정보</button>`}<button onclick="logout()">로그아웃</button></div></div></div><div class="wrap">${content}</div>${mobileNav()}<div class="footer">WITH Welfare Mall V17 Final</div>`}
function mobileNav(){if(!session)return "";const items=[["home","⌂","홈"],["stay","🏡","숙소"],["family","🎁","경조"],["event","🎉","행사"],[session.role==="admin"?"admin":"mypage","☰",session.role==="admin"?"관리":"내정보"]];return `<nav class="mobile-bottom-nav">${items.map(i=>`<button class="${page===i[0]?'active':''}" onclick="setPage('${i[0]}')"><span>${i[1]}</span><small>${i[2]}</small></button>`).join("")}</nav>`}

function home(){const u=user();const approved=state.reservations.filter(r=>r.userId===u.id&&r.status==="승인");return layout(`<section class="hero"><div class="welcome"><span class="badge">${state.settings.homeBadge}</span><h1>${state.settings.homeTitle}</h1><p class="muted">${state.settings.homeDescription}</p><button onclick="setPage('stay')">숙소 예약하기</button> <button class="secondary" onclick="setPage('vacation')">휴가지원사업 신청</button></div><div class="panel"><h3>운영 상태</h3><p class="muted">${cloudStatus}</p><p class="muted">관리자 1명 운영 / 직원 25명 규모 기준</p></div></section><section class="section"><h2>승인된 숙소 예약</h2>${approved.length?`<div class="grid2">${approved.map(r=>`<div class="card"><h3>${r.roomName}</h3><p>${r.checkin} ~ ${r.checkout}</p><p><span class="status">${r.stayStatus||"이용대기"}</span></p><button onclick="showRoomManual('${r.id}')">숙소 사용 설명 보기</button></div>`).join("")}</div>`:`<div class="panel empty">승인된 숙소 예약이 없습니다.</div>`}</section><section class="grid4">${["stay","family","event","discount","vacation","notice"].filter(enabled).map(k=>`<div class="card"><h3>${pageLabel(k)}</h3><p class="muted">바로가기</p><button onclick="setPage('${k}')">열기</button></div>`).join("")}</section>`)}
function showRoomManual(resId){const r=state.reservations.find(x=>x.id===resId&&x.userId===user().id&&x.status==="승인");if(!r)return toast("승인된 예약자만 볼 수 있습니다.");const room=state.rooms.find(x=>x.id===r.roomId);alert(`[${room.name} 사용 설명]\n\n${room.manual||"관리자가 아직 사용 설명을 등록하지 않았습니다."}`)}

function days(a,b){return Math.max(0,Math.round((new Date(b)-new Date(a))/86400000))}
function overlaps(a,b,c,d){return a<d&&c<b}
function available(roomId,ci,co){return !state.reservations.some(r=>r.roomId===roomId&&r.status!=="취소"&&r.status!=="반려"&&overlaps(ci,co,r.checkin,r.checkout))}
function price(policyId,n){const p=state.policies.find(x=>x.id===policyId);if(!p||!p.paymentRequired)return 0;return Math.round(state.settings.nightlyPrice*n*(100-p.discountRate)/100)}
function stay(){return layout(`<section class="section"><h2>${pageLabel("stay")}</h2><div class="grid2">${state.rooms.map(r=>`<div class="card">${roomPhoto(r)}<h3>${r.name}</h3><p class="muted">기본 ${r.basePeople}명 / 최대 ${r.maxPeople}명</p><p class="muted">${r.address}</p><button onclick="reserveForm('${r.id}')">예약 신청</button></div>`).join("")}</div></section><section id="reserveTarget"></section><section class="section"><h2>예약 현황</h2>${calendar()}</section><section class="section"><h2>내 예약</h2>${reservationTable(state.reservations.filter(r=>r.userId===user().id),false)}</section>`)}
function roomPhoto(r){return `<div class="room-photo">${r.photos&&r.photos[0]?`<img src="${r.photos[0].data||r.photos[0]}">`:r.name}</div>`}
function reserveForm(id){const r=state.rooms.find(x=>x.id===id);document.getElementById("reserveTarget").innerHTML=`<div class="panel"><h3>${r.name} 예약 신청</h3><form class="form" onsubmit="reserve(event,'${id}')"><label>체크인<input type="date" name="checkin" required></label><label>체크아웃<input type="date" name="checkout" required></label><label>이용구분<select name="policy">${state.policies.map(p=>`<option value="${p.id}">${p.name}</option>`).join("")}</select></label><label>인원<input type="number" name="people" value="${r.basePeople}" min="1" max="${r.maxPeople}"></label><label class="wide">메모<textarea name="memo"></textarea></label><button class="wide">예약 신청</button></form></div>`}
function reserve(e,id){e.preventDefault();const f=new FormData(e.target),ci=f.get("checkin"),co=f.get("checkout");if(co<=ci)return toast("날짜를 확인해 주세요.");if(!available(id,ci,co))return toast("이미 예약된 날짜입니다.");const room=state.rooms.find(r=>r.id===id),n=days(ci,co),policy=state.policies.find(p=>p.id===f.get("policy"));state.reservations.push({id:uid(),userId:user().id,userName:user().name,dept:user().dept||"",phone:user().phone||"",roomId:id,roomName:room.name,checkin:ci,checkout:co,nights:n,people:+f.get("people"),useType:policy.name,amount:price(policy.id,n),status:"접수완료",stayStatus:"이용대기",memo:f.get("memo"),createdAt:new Date().toLocaleString()});save();toast("예약 신청 접수 완료");render()}
function calendar(){const y=calMonth.getFullYear(),m=calMonth.getMonth();const first=new Date(y,m,1),start=new Date(first);start.setDate(first.getDate()-first.getDay());let html=`<div class="actions"><button class="secondary" onclick="calMonth.setMonth(calMonth.getMonth()-1);render()">이전</button><button class="secondary">${y}.${String(m+1).padStart(2,"0")}</button><button class="secondary" onclick="calMonth.setMonth(calMonth.getMonth()+1);render()">다음</button></div><div class="calendar">`;["일","월","화","수","목","금","토"].forEach(d=>html+=`<div class="day"><b>${d}</b></div>`);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=d.toISOString().slice(0,10);const marks=state.reservations.filter(r=>r.status!=="취소"&&r.status!=="반려"&&ds>=r.checkin&&ds<r.checkout).map(r=>`<span class="mark">${r.roomName} X</span>`).join("");html+=`<div class="day ${d.getMonth()!==m?'out':''}"><div class="daynum">${d.getDate()}</div>${marks}</div>`}return html+"</div>"}
function reservationTable(rows,admin){if(!rows.length)return `<div class="panel empty">예약 내역 없음</div>`;return `${admin?bulkToolbar("reservations","숙소 예약","chkRes"):""}<table class="table"><thead><tr>${admin?`<th>선택</th>`:""}<th>숙소</th><th>신청자</th><th>기간</th><th>구분/금액</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(r=>`<tr>${admin?`<td>${check("chkRes",r.id)}</td>`:""}<td>${r.roomName}</td><td>${r.userName}<br>${r.dept||""}</td><td>${r.checkin}~${r.checkout}<br>${r.nights}박</td><td>${r.useType}<br>${money(r.amount)}</td><td><span class="status ${r.status}">${r.status}</span><br><span class="status ${r.stayStatus||""}">${r.stayStatus||""}</span></td><td class="actions">${admin?adminStatusButtons("reservations",r):userReservationButtons(r)}</td></tr>`).join("")}</tbody></table>`}
function userReservationButtons(r){let h="";if(r.status==="접수완료")h+=`<button class="danger" onclick="cancelOwn('reservations','${r.id}')">취소</button>`;if(r.status==="승인"){if(r.stayStatus==="이용대기")h+=`<button onclick="stayCheck('${r.id}','체크인완료')">체크인</button>`;if(r.stayStatus==="체크인완료")h+=`<button onclick="stayCheck('${r.id}','체크아웃완료')">체크아웃</button>`;h+=`<button class="secondary" onclick="showRoomManual('${r.id}')">사용 설명</button>`}return h||"-"}
function stayCheck(id,status){const r=state.reservations.find(x=>x.id===id&&x.userId===user().id&&x.status==="승인");if(!r)return toast("승인된 예약만 처리 가능합니다.");r.stayStatus=status;save();toast(status+" 처리되었습니다.");render()}

function family(){const u=user();return layout(`<section class="section"><h2>${pageLabel("family")}</h2><div class="panel"><form class="form" onsubmit="submitCondolence(event)"><label>성명<input value="${u.name}" name="userName" readonly></label><label>소속<input value="${u.dept||""}" name="dept" readonly></label><label>직위<input name="position" required></label><label>연락처<input value="${u.phone||""}" name="contact" required></label><label>신청구분<select name="type" onchange="this.form.amount.value=condolenceAmount(this.value)">${state.condolenceTypes.map(t=>`<option value="${t.name}">${t.name}</option>`).join("")}</select></label><label>신청금액<input name="amount" type="number" value="${state.condolenceTypes[0]?.amount||0}" readonly></label><label class="wide">경조내용<input name="content" required></label><label>경조일자<input type="date" name="eventDate" required></label><label>경조대상자 성명<input name="targetName" required></label><label>경조대상자 생년월일<input type="date" name="targetBirth"></label><label class="wide">신청인과의 관계<input name="targetRelation" required></label><label class="wide">증빙자료 PDF/이미지<input type="file" name="file" accept=".pdf,image/*"></label><button class="wide">경조사 신청</button></form></div><section class="section"><h2>내 신청 현황</h2>${condolenceTable(state.condolences.filter(c=>c.userId===u.id),false)}</section></section>`)}
function condolenceAmount(type){return (state.condolenceTypes.find(t=>t.name===type)||{}).amount||0}
function submitCondolence(e){e.preventDefault();const f=new FormData(e.target),file=e.target.file.files[0];const row={id:uid(),userId:user().id,userName:f.get("userName"),dept:f.get("dept"),position:f.get("position"),contact:f.get("contact"),type:f.get("type"),amount:+f.get("amount"),content:f.get("content"),eventDate:f.get("eventDate"),targetName:f.get("targetName"),targetBirth:f.get("targetBirth"),targetRelation:f.get("targetRelation"),attachment:"",fileName:file?.name||"",status:"접수완료",createdAt:new Date().toLocaleString()};const done=()=>{state.condolences.push(row);save();toast("접수 완료");render()};if(file){const reader=new FileReader();reader.onload=()=>{row.attachment=reader.result;done()};reader.readAsDataURL(file)}else done()}
function condolenceTable(rows,admin){if(!rows.length)return `<div class="panel empty">신청 내역 없음</div>`;return `${admin?bulkToolbar("condolences","경조사 접수","chkCon"):""}<table class="table"><thead><tr>${admin?`<th>선택</th>`:""}<th>신청자</th><th>구분</th><th>내용/대상</th><th>금액</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(c=>`<tr>${admin?`<td>${check("chkCon",c.id)}</td>`:""}<td>${c.userName}<br>${c.dept||""}/${c.position||""}</td><td>${c.type}<br>${c.eventDate}</td><td>${c.content}<br>${c.targetName}/${c.targetRelation}</td><td>${money(c.amount)}</td><td><span class="status ${c.status}">${c.status}</span></td><td class="actions">${admin?adminStatusButtons("condolences",c)+`<button onclick="previewCondolenceId='${c.id}';render()">미리보기</button><button onclick="printCondolence('${c.id}')">출력</button>${c.attachment?`<button class="secondary" onclick="openAttach('${c.attachment}')">증빙</button>`:""}`:"-"}</td></tr>`).join("")}</tbody></table>`}
function a4(c){return `<div class="a4"><div class="a4-head"><h1>경조금 지급 신청서</h1><table class="approval"><tr><th>신청자</th><th>경영총괄</th></tr><tr><td>${c.userName||""}</td><td></td></tr></table></div><h2>1. 인적사항</h2><table class="form"><tr><th>성 명</th><td>${c.userName}</td><th>소 속</th><td>${c.dept||""}</td></tr><tr><th>직 위</th><td>${c.position||""}</td><th>연락처</th><td>${c.contact||""}</td></tr></table><h2>2. 경조사항</h2><table class="form"><tr><th>신청구분</th><td colspan="3" class="center">${c.type}</td></tr><tr><th>경조내용</th><td>${c.content||""}</td><th>신청금액</th><td>${money(c.amount)}</td></tr><tr><th>경조일자</th><td colspan="3" class="center">${c.eventDate||""}</td></tr><tr><th>경조대상자</th><td colspan="3">- 생년월일 : ${c.targetBirth||""}<br>- 성명 : ${c.targetName||""}<br>- 신청인과의 관계 : ${c.targetRelation||""}</td></tr></table><div class="note">* 근조화환 여부는 경조금 지급 기준을 따른다.<br>* 증빙자료는 별도 첨부파일을 확인한다.</div><p class="center">상기의 내용으로 경조금의 지급을 신청합니다.</p><div class="date">${new Date().toLocaleDateString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}).replace(/\. /g,"년 ").replace(".","일")}</div><div class="sign">신청자 : ${c.userName}</div></div>`}
function printCondolence(id){const c=state.condolences.find(x=>x.id===id);const w=window.open("","_blank");w.document.write(`<html><head><link rel="stylesheet" href="style.css"><title>경조금 지급 신청서</title></head><body><div class="no-print" style="padding:10px;text-align:center"><button onclick="window.print()">A4 출력/PDF 저장</button></div><div class="print-only">${a4(c)}</div></body></html>`);w.document.close()}
function openAttach(data){const w=window.open("","_blank");w.document.write(`<html><body style="margin:20px"><button onclick="window.print()">출력</button><hr>${String(data).startsWith("data:image")?`<img src="${data}" style="max-width:100%">`:`<iframe src="${data}" style="width:100%;height:90vh"></iframe>`}</body></html>`)}
function eventPage(){return layout(`<section class="section"><h2>${pageLabel("event")}</h2><div class="grid2">${state.events.filter(e=>e.open).map(ev=>`<div class="card"><h3>${ev.title}</h3><p>${ev.date||""}</p><p class="muted">${ev.memo||""}</p><button onclick="applyEvent('${ev.id}')">참석 신청</button></div>`).join("")}</div><section class="section"><h2>내 신청 현황</h2>${eventAppTable(state.eventApplications.filter(a=>a.userId===user().id),false)}</section></section>`)}
function applyEvent(id){const ev=state.events.find(e=>e.id===id);if(state.eventApplications.some(a=>a.eventId===id&&a.userId===user().id&&a.status!=="취소"))return toast("이미 신청했습니다.");state.eventApplications.push({id:uid(),eventId:id,title:ev.title,userId:user().id,userName:user().name,dept:user().dept||"",phone:user().phone||"",status:"접수완료",createdAt:new Date().toLocaleString()});save();toast("신청 접수 완료");render()}
function eventAppTable(rows,admin){if(!rows.length)return `<div class="panel empty">신청 내역 없음</div>`;return `${admin?bulkToolbar("eventApplications","행사 신청","chkEvent"):""}<table class="table"><thead><tr>${admin?`<th>선택</th>`:""}<th>행사</th><th>신청자</th><th>부서</th><th>연락처</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(a=>`<tr>${admin?`<td>${check("chkEvent",a.id)}</td>`:""}<td>${a.title}</td><td>${a.userName}</td><td>${a.dept}</td><td>${a.phone}</td><td><span class="status ${a.status}">${a.status}</span></td><td class="actions">${admin?adminStatusButtons("eventApplications",a):"-"}</td></tr>`).join("")}</tbody></table>`}
function discount(){return layout(`<section class="section"><h2>${pageLabel("discount")}</h2><div class="grid3">${state.discounts.map(d=>{const cnt=state.discountApplications.filter(a=>a.discountId===d.id&&a.status!=="취소").length,closed=d.applyEnabled&&d.limitCount&&cnt>=d.limitCount;return `<div class="card"><span class="badge">${d.category}</span><h3>${d.title}</h3><p>${d.rate}</p><p class="muted">${d.method}</p>${d.applyEnabled?`<p>신청 ${cnt}/${d.limitCount||"무제한"}</p><button ${closed?'disabled':''} onclick="applyDiscount('${d.id}')">${closed?"마감":"이용하기"}</button>`:`<button onclick="${d.link?`window.open('${d.link}')`:"toast('이용 방법을 확인하세요.')"}">이용하기</button>`}</div>`}).join("")}</div><section class="section"><h2>내 신청 현황</h2>${discountAppTable(state.discountApplications.filter(a=>a.userId===user().id),false)}</section></section>`)}
function applyDiscount(id){const d=state.discounts.find(x=>x.id===id);if(state.discountApplications.some(a=>a.discountId===id&&a.userId===user().id&&a.status!=="취소"))return toast("이미 신청했습니다.");const cnt=state.discountApplications.filter(a=>a.discountId===id&&a.status!=="취소").length;if(d.limitCount&&cnt>=d.limitCount)return toast("마감되었습니다.");state.discountApplications.push({id:uid(),discountId:id,title:d.title,userId:user().id,userName:user().name,dept:user().dept||"",phone:user().phone||"",status:"접수완료",createdAt:new Date().toLocaleString()});save();toast("신청 접수 완료");render()}
function discountAppTable(rows,admin){if(!rows.length)return `<div class="panel empty">신청 내역 없음</div>`;return `${admin?bulkToolbar("discountApplications","할인 신청","chkDiscount"):""}<table class="table"><thead><tr>${admin?`<th>선택</th>`:""}<th>혜택</th><th>신청자</th><th>부서</th><th>연락처</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(a=>`<tr>${admin?`<td>${check("chkDiscount",a.id)}</td>`:""}<td>${a.title}</td><td>${a.userName}</td><td>${a.dept}</td><td>${a.phone}</td><td><span class="status ${a.status}">${a.status}</span></td><td class="actions">${admin?adminStatusButtons("discountApplications",a):"-"}</td></tr>`).join("")}</tbody></table>`}
function vacation(){const u=user();return layout(`<section class="section"><h2>${pageLabel("vacation")}</h2><div class="panel"><form class="form" onsubmit="applyVacation(event)"><label>신청자명<input name="userName" value="${u.name}" readonly></label><label>부서<input name="dept" value="${u.dept||""}" readonly></label><label>연락처<input name="phone" value="${u.phone||""}" readonly></label><label class="wide">신청사유<textarea name="memo" required></textarea></label><button class="wide">신청 접수</button></form></div><section class="section"><h2>내 신청 현황</h2>${vacationTable(state.vacationSupport.filter(v=>v.userId===u.id),false)}</section></section>`)}
function applyVacation(e){e.preventDefault();const f=new FormData(e.target);state.vacationSupport.push({id:uid(),userId:user().id,userName:f.get("userName"),dept:f.get("dept"),phone:f.get("phone"),memo:f.get("memo"),status:"접수완료",createdAt:new Date().toLocaleString()});save();toast("신청 접수 완료");render()}
function vacationTable(rows,admin){if(!rows.length)return `<div class="panel empty">신청 내역 없음</div>`;return `${admin?bulkToolbar("vacationSupport","휴가지원 신청","chkVac"):""}<table class="table"><thead><tr>${admin?`<th>선택</th>`:""}<th>신청자명</th><th>부서</th><th>연락처</th><th>사유</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(v=>`<tr>${admin?`<td>${check("chkVac",v.id)}</td>`:""}<td>${v.userName}</td><td>${v.dept}</td><td>${v.phone}</td><td>${v.memo}</td><td><span class="status ${v.status}">${v.status}</span></td><td class="actions">${admin?adminStatusButtons("vacationSupport",v):v.status==="접수완료"?`<button class="danger" onclick="cancelOwn('vacationSupport','${v.id}')">취소</button>`:"-"}</td></tr>`).join("")}</tbody></table>`}
function notice(){return layout(`<section class="section"><h2>${pageLabel("notice")}</h2>${state.notices.length?state.notices.map(n=>`<div class="card"><h3>${n.important?"[중요] ":""}${n.title}</h3><p>${n.body}</p></div>`).join(""):`<div class="panel empty">공지 없음</div>`}</section>`)}
function mypage(){return layout(`<section class="section"><h2>내 정보</h2><div class="panel"><p>${user().name} / ${user().dept||""} / ${user().phone||""}</p></div></section>`)}
function cancelOwn(key,id){const r=state[key].find(x=>x.id===id&&x.userId===user().id);if(!r)return;r.status="취소";save();render();toast("취소되었습니다.")}

function admin(){const tabs=[["dashboard","대시보드"],["home","홈/메뉴/로고"],["stay","숙소 관리"],["family","경조사 관리"],["event","행사 관리"],["discount","할인 관리"],["vacation","휴가지원사업"],["notice","공지 관리"],["users","회원/관리자"],["logs","감사 로그"],["stats","통계"]];let body="";if(adminTab==="dashboard")body=adminDashboard();if(adminTab==="home")body=adminHome();if(adminTab==="stay")body=adminStay();if(adminTab==="family")body=adminFamily();if(adminTab==="event")body=adminEvent();if(adminTab==="discount")body=adminDiscount();if(adminTab==="vacation")body=`<h2>휴가지원사업 접수 현황</h2>${vacationTable(state.vacationSupport,true)}`;if(adminTab==="notice")body=adminNotice();if(adminTab==="users")body=adminUsers();if(adminTab==="logs")body=`${bulkToolbar("auditLogs","감사 로그","chkLog")}<table class="table"><tbody>${state.auditLogs.map(l=>`<tr><td>${check("chkLog",l.id)}</td><td>${l.createdAt}</td><td>${l.actor}</td><td>${l.action}</td><td>${l.detail}</td></tr>`).join("")}</tbody></table>`;if(adminTab==="stats")body=adminStats();return layout(`<section class="admin-shell"><aside class="admin-side">${tabs.map(t=>`<button class="${adminTab===t[0]?'active':''}" onclick="adminTab='${t[0]}';render()">${t[1]}</button>`).join("")}</aside><main>${body}</main></section>`)}
function adminDashboard(){return `<div class="grid4"><div class="card"><b>회원</b><h2>${state.users.length}</h2></div><div class="card"><b>숙소예약</b><h2>${state.reservations.length}</h2></div><div class="card"><b>경조사</b><h2>${state.condolences.length}</h2></div><div class="card"><b>상태</b><p>${cloudStatus}</p></div></div><section class="section"><h2>데이터 정리</h2>${dataCleanup()}</section>`}
function dataCleanup(){const list=[["reservations","숙소 예약"],["condolences","경조사 접수"],["eventApplications","행사 신청"],["discountApplications","할인 신청"],["vacationSupport","휴가지원 신청"],["auditLogs","감사 로그"]];return `<table class="table"><tbody>${list.map(i=>`<tr><td>${i[1]}</td><td>${state[i[0]].length}건</td><td><button class="danger" onclick="clearRows('${i[0]}','${i[1]}')">전체삭제</button></td></tr>`).join("")}</tbody></table>`}
function adminHome(){return `<div class="panel"><form class="form" onsubmit="saveHome(event)"><label>뱃지<input name="homeBadge" value="${state.settings.homeBadge}"></label><label>제목<input name="homeTitle" value="${state.settings.homeTitle}"></label><label class="wide">설명<textarea name="homeDescription">${state.settings.homeDescription}</textarea></label><label class="wide">로고 이미지<input type="file" name="logo" accept="image/*"></label><button class="wide">저장</button></form></div><section class="section"><h2>메뉴 설정</h2>${Object.entries(state.menu).map(([k,m])=>`<div class="card"><div class="form"><label>메뉴명<input id="mn_${k}" value="${m.name}"></label><label>상태<select id="me_${k}"><option value="true" ${m.enabled?"selected":""}>활성</option><option value="false" ${!m.enabled?"selected":""}>비활성</option></select></label><button class="wide" onclick="saveMenu('${k}')">저장</button></div></div>`).join("")}</section>`}
function saveHome(e){e.preventDefault();const f=new FormData(e.target);state.settings.homeBadge=f.get("homeBadge");state.settings.homeTitle=f.get("homeTitle");state.settings.homeDescription=f.get("homeDescription");const file=e.target.logo.files[0];const done=()=>{save();toast("저장됨");render()};if(file){const r=new FileReader();r.onload=()=>{state.settings.logo=r.result;done()};r.readAsDataURL(file)}else done()}
function saveMenu(k){state.menu[k].name=document.getElementById("mn_"+k).value;state.menu[k].enabled=document.getElementById("me_"+k).value==="true";save();render()}
function adminStay(){return `<h2>숙소 관리</h2><div class="grid2">${state.rooms.map(r=>`<div class="card"><h3>${r.name}</h3>${roomPhoto(r)}<form class="form" onsubmit="saveRoom(event,'${r.id}')"><label>기본인원<input name="basePeople" type="number" value="${r.basePeople}"></label><label>최대인원<input name="maxPeople" type="number" value="${r.maxPeople}"></label><label class="wide">주소<input name="address" value="${r.address}"></label><label class="wide">숙소 사용 설명서<textarea name="manual">${r.manual||""}</textarea></label><label class="wide">대표 사진<input type="file" name="photo" accept="image/*"></label><button class="wide">숙소 정보 저장</button></form></div>`).join("")}</div><section class="section"><h2>숙소 예약 접수 현황</h2>${reservationTable(state.reservations,true)}</section>`}
function saveRoom(e,id){e.preventDefault();const r=state.rooms.find(x=>x.id===id),f=new FormData(e.target);r.basePeople=+f.get("basePeople");r.maxPeople=+f.get("maxPeople");r.address=f.get("address");r.manual=f.get("manual");const file=e.target.photo.files[0];const done=()=>{save();toast("저장됨");render()};if(file){const reader=new FileReader();reader.onload=()=>{r.photos=[{data:reader.result,name:file.name}];done()};reader.readAsDataURL(file)}else done()}
function adminFamily(){const sel=state.condolences.find(c=>c.id===previewCondolenceId)||state.condolences[0];return `<div class="grid2"><div><h2>경조사 구분 관리</h2><div class="panel"><form class="form" onsubmit="addConType(event)"><label>구분명<input name="name" required></label><label>설명<input name="desc"></label><label>신청금액<input name="amount" type="number" value="0"></label><button class="wide">구분 추가</button></form></div><table class="table"><thead><tr><th>구분명</th><th>설명</th><th>신청금액</th><th>관리</th></tr></thead><tbody>${state.condolenceTypes.map(t=>`<tr><td><input id="ctn_${t.id}" value="${t.name}"></td><td><input id="ctd_${t.id}" value="${t.desc||""}"></td><td><input id="cta_${t.id}" type="number" value="${t.amount||0}"></td><td class="actions"><button onclick="saveConType('${t.id}')">수정</button><button class="danger" onclick="delConType('${t.id}')">삭제</button></td></tr>`).join("")}</tbody></table><section class="section"><h2>경조사 접수 현황</h2>${condolenceTable(state.condolences,true)}</section></div><div class="print-preview"><div class="subtle-title"><h3>신청서 출력 미리보기</h3>${sel?`<button onclick="printCondolence('${sel.id}')">출력</button>`:""}</div>${sel?a4(sel):`<div class="empty">접수 건을 선택하면 미리보기가 표시됩니다.</div>`}</div></div>`}
function addConType(e){e.preventDefault();const f=new FormData(e.target);state.condolenceTypes.push({id:uid(),name:f.get("name"),desc:f.get("desc"),amount:+f.get("amount")});save();render()}
function saveConType(id){const t=state.condolenceTypes.find(x=>x.id===id);t.name=document.getElementById("ctn_"+id).value;t.desc=document.getElementById("ctd_"+id).value;t.amount=+document.getElementById("cta_"+id).value;save();toast("수정됨");render()}
function delConType(id){if(confirm("삭제할까요?")){state.condolenceTypes=state.condolenceTypes.filter(x=>x.id!==id);save();render()}}
function adminEvent(){return `<h2>행사 관리</h2><div class="panel"><form class="form" onsubmit="addEvent(event)"><label>행사명<input name="title" required></label><label>일자<input type="date" name="date"></label><label>인원제한<input type="number" name="limit" value="0"></label><label class="wide">내용<textarea name="memo"></textarea></label><button class="wide">행사 추가</button></form></div><table class="table"><tbody>${state.events.map(ev=>`<tr><td>${ev.title}</td><td>${ev.date}</td><td>${ev.memo}</td><td><button class="danger" onclick="state.events=state.events.filter(x=>x.id!=='${ev.id}');save();render()">삭제</button></td></tr>`).join("")}</tbody></table><section class="section"><h2>행사 신청 현황</h2>${eventAppTable(state.eventApplications,true)}</section>`}
function addEvent(e){e.preventDefault();const f=new FormData(e.target);state.events.push({id:uid(),title:f.get("title"),date:f.get("date"),limit:+f.get("limit"),memo:f.get("memo"),open:true});save();render()}
function adminDiscount(){return `<h2>할인 관리</h2><div class="panel"><form class="form" onsubmit="addDiscount(event)"><label>카테고리<input name="category" required></label><label>제목<input name="title" required></label><label>할인내용<input name="rate" required></label><label>신청접수<select name="applyEnabled"><option value="false">일반안내</option><option value="true">신청접수</option></select></label><label>제한인원<input type="number" name="limitCount" value="0"></label><label>링크<input name="link"></label><label class="wide">이용방법<textarea name="method"></textarea></label><button class="wide">추가</button></form></div><table class="table"><thead><tr><th>카테고리</th><th>제목</th><th>내용</th><th>신청/제한</th><th>관리</th></tr></thead><tbody>${state.discounts.map(d=>`<tr><td><input id="dc_${d.id}" value="${d.category}"></td><td><input id="dt_${d.id}" value="${d.title}"></td><td><input id="dr_${d.id}" value="${d.rate}"></td><td><select id="da_${d.id}"><option value="false" ${!d.applyEnabled?"selected":""}>일반</option><option value="true" ${d.applyEnabled?"selected":""}>신청</option></select><input id="dl_${d.id}" type="number" value="${d.limitCount||0}"></td><td class="actions"><button onclick="saveDiscount('${d.id}')">수정</button><button class="danger" onclick="delDiscount('${d.id}')">삭제</button></td></tr>`).join("")}</tbody></table><section class="section"><h2>할인 신청 현황</h2>${discountAppTable(state.discountApplications,true)}</section>`}
function addDiscount(e){e.preventDefault();const f=new FormData(e.target);state.discounts.push({id:uid(),category:f.get("category"),title:f.get("title"),rate:f.get("rate"),method:f.get("method"),link:f.get("link"),applyEnabled:f.get("applyEnabled")==="true",limitCount:+f.get("limitCount")});save();render()}
function saveDiscount(id){const d=state.discounts.find(x=>x.id===id);d.category=document.getElementById("dc_"+id).value;d.title=document.getElementById("dt_"+id).value;d.rate=document.getElementById("dr_"+id).value;d.applyEnabled=document.getElementById("da_"+id).value==="true";d.limitCount=+document.getElementById("dl_"+id).value;save();toast("수정됨");render()}
function delDiscount(id){if(confirm("삭제할까요?")){state.discounts=state.discounts.filter(x=>x.id!==id);save();render()}}
function adminNotice(){return `<h2>공지 관리</h2><div class="panel"><form class="form" onsubmit="addNotice(event)"><label>제목<input name="title" required></label><label>중요<select name="important"><option value="false">일반</option><option value="true">중요</option></select></label><label class="wide">내용<textarea name="body" required></textarea></label><button class="wide">공지 추가</button></form></div><table class="table"><tbody>${state.notices.map(n=>`<tr><td>${n.important?"[중요] ":""}${n.title}</td><td>${n.body}</td><td><button class="danger" onclick="state.notices=state.notices.filter(x=>x.id!=='${n.id}');save();render()">삭제</button></td></tr>`).join("")}</tbody></table>`}
function addNotice(e){e.preventDefault();const f=new FormData(e.target);state.notices.push({id:uid(),title:f.get("title"),body:f.get("body"),important:f.get("important")==="true",createdAt:new Date().toLocaleString()});save();render()}
function adminUsers(){return `<h2>회원 관리</h2><table class="table"><thead><tr><th>이름</th><th>부서</th><th>전화</th><th>상태</th><th>관리</th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${u.name}</td><td>${u.dept}</td><td>${u.phone}</td><td>${u.status}</td><td class="actions"><button onclick="uStatus('${u.id}','승인')">승인</button><button class="danger" onclick="state.users=state.users.filter(x=>x.id!=='${u.id}');save();render()">삭제</button></td></tr>`).join("")}</tbody></table>`}
function uStatus(id,s){state.users.find(x=>x.id===id).status=s;save();render()}
function adminStats(){return `<div class="grid4"><div class="card"><h3>예약</h3><h2>${state.reservations.length}</h2></div><div class="card"><h3>경조사</h3><h2>${state.condolences.length}</h2></div><div class="card"><h3>행사신청</h3><h2>${state.eventApplications.length}</h2></div><div class="card"><h3>휴가지원</h3><h2>${state.vacationSupport.length}</h2></div></div>`}

function check(cls,id){return `<input type="checkbox" class="${cls}" value="${id}">`}
function selected(cls){return Array.from(document.querySelectorAll("."+cls+":checked")).map(x=>x.value)}
function bulkToolbar(key,label,cls){return `<div class="bulk-toolbar"><button class="secondary" onclick="document.querySelectorAll('.${cls}').forEach(x=>x.checked=true)">전체선택</button><button class="danger" onclick="deleteSelected('${key}','${label}','${cls}')">선택삭제</button><button class="danger" onclick="clearRows('${key}','${label}')">전체삭제</button></div>`}
function deleteSelected(key,label,cls){const ids=selected(cls);if(!ids.length)return toast("선택된 항목이 없습니다.");if(confirm(`${label} ${ids.length}건 삭제할까요?`)){state[key]=state[key].filter(x=>!ids.includes(x.id));save();render()}}
function clearRows(key,label){if(confirm(`${label} 전체 삭제할까요?`)){state[key]=[];save();render()}}
function adminStatusButtons(key,row){return `<button onclick="setStatus('${key}','${row.id}','승인')">승인</button><button class="danger" onclick="setStatus('${key}','${row.id}','반려')">반려</button><button class="danger" onclick="deleteOne('${key}','${row.id}')">삭제</button>`}
function setStatus(key,id,status){const r=state[key].find(x=>x.id===id);r.status=status;save();render()}
function deleteOne(key,id){if(confirm("삭제할까요?")){state[key]=state[key].filter(x=>x.id!==id);save();render()}}

function render(){normalize();if(!session)return loginView();if(!user()){logout();return}if(page==="home")app.innerHTML=home();if(page==="stay")app.innerHTML=stay();if(page==="family")app.innerHTML=family();if(page==="event")app.innerHTML=eventPage();if(page==="discount")app.innerHTML=discount();if(page==="vacation")app.innerHTML=vacation();if(page==="notice")app.innerHTML=notice();if(page==="mypage")app.innerHTML=mypage();if(page==="admin")app.innerHTML=admin()}
initCloud();
